# Generated by Django 6.0.6 on 2026-06-23 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Klient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imie", models.CharField(max_length=50)),
                ("nazwisko", models.CharField(max_length=50)),
                ("telefon", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("adres", models.CharField(max_length=255)),
                ("nazwa_firmy", models.CharField(blank=True, max_length=100)),
                ("nip", models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Magazyn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=100)),
                ("adres", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=100)),
                ("producent", models.CharField(blank=True, max_length=100)),
                ("grubosc_mm", models.DecimalField(decimal_places=2, max_digits=5)),
                ("cena_za_m2", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="RozmiarBlachy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=100)),
                ("szerokosc_mm", models.IntegerField()),
                ("wysokosc_mm", models.IntegerField()),
                ("standardowy", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="TypUslugi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=100)),
                ("jednostka", models.CharField(default="szt.", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="PracownikProfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telefon", models.CharField(blank=True, max_length=20)),
                (
                    "rola",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrator"),
                            ("MAGAZYN", "Magazynier"),
                            ("PRODUKCJA", "Pracownik produkcji"),
                            ("KSIEGOWOSC", "Księgowość"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcesMagazynowy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "typ",
                    models.CharField(
                        choices=[
                            ("PRZYJECIE", "Przyjęcie materiału"),
                            ("WYDANIE", "Wydanie materiału"),
                            ("INWENTARYZACJA", "Inwentaryzacja"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ilosc", models.IntegerField()),
                ("data", models.DateTimeField(auto_now_add=True)),
                ("opis", models.TextField(blank=True)),
                (
                    "magazyn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.magazyn"
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.material"
                    ),
                ),
                (
                    "pracownik",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cennik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cena", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_od", models.DateField()),
                (
                    "typ_uslugi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.typuslugi"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Zamowienie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_utworzenia", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRZYJETE", "Przyjęte"),
                            ("REALIZACJA", "W realizacji"),
                            ("GOTOWE", "Gotowe do odbioru"),
                            ("ZAKONCZONE", "Zakończone"),
                            ("ANULOWANE", "Anulowane"),
                        ],
                        default="PRZYJETE",
                        max_length=20,
                    ),
                ),
                ("uwagi", models.TextField(blank=True)),
                (
                    "klient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.klient"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PozycjaZamowienia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ilosc", models.PositiveIntegerField(default=1)),
                (
                    "cena",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRZYJETA", "Przyjęta"),
                            ("REALIZACJA", "W realizacji"),
                            ("ZREALIZOWANA", "Zrealizowana"),
                            ("ODRZUCONA", "Odrzucona"),
                        ],
                        default="PRZYJETA",
                        max_length=20,
                    ),
                ),
                ("czy_powstal_odpad", models.BooleanField(default=False)),
                ("opis_odpadu", models.TextField(blank=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.material"
                    ),
                ),
                (
                    "przypisany_pracownik",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rozmiar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.rozmiarblachy",
                    ),
                ),
                (
                    "typ_uslugi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.typuslugi",
                    ),
                ),
                (
                    "zamowienie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pozycje",
                        to="core.zamowienie",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Platnosc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kwota", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "rabat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NIEOPLACONA", "Nieopłacona"),
                            ("OPLACONA", "Opłacona"),
                            ("ANULOWANA", "Anulowana"),
                        ],
                        default="NIEOPLACONA",
                        max_length=20,
                    ),
                ),
                ("data_utworzenia", models.DateTimeField(auto_now_add=True)),
                (
                    "zamowienie",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.zamowienie",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StanMagazynowy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ilosc", models.IntegerField(default=0)),
                (
                    "magazyn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.magazyn"
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.material"
                    ),
                ),
            ],
            options={
                "unique_together": {("magazyn", "material")},
            },
        ),
    ]
