# Generated by Django 4.2.27 on 2026-06-24 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pozycjazamowienia",
            old_name="cena",
            new_name="cena_jednostkowa",
        ),
        migrations.RemoveField(
            model_name="pozycjazamowienia",
            name="czy_powstal_odpad",
        ),
        migrations.RemoveField(
            model_name="pozycjazamowienia",
            name="opis_odpadu",
        ),
        migrations.RemoveField(
            model_name="pozycjazamowienia",
            name="przypisany_pracownik",
        ),
        migrations.RemoveField(
            model_name="pozycjazamowienia",
            name="status",
        ),
        migrations.RemoveField(
            model_name="rozmiarblachy",
            name="nazwa",
        ),
        migrations.RemoveField(
            model_name="rozmiarblachy",
            name="standardowy",
        ),
        migrations.RemoveField(
            model_name="typuslugi",
            name="jednostka",
        ),
        migrations.AddField(
            model_name="pozycjazamowienia",
            name="czy_niestandardowy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pozycjazamowienia",
            name="szerokosc_niestandardowa_mm",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pozycjazamowienia",
            name="wartosc",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="pozycjazamowienia",
            name="wysokosc_niestandardowa_mm",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="procesmagazynowy",
            name="cofnieta",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="procesmagazynowy",
            name="cofnieta_przez",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cofniete_operacje_magazynowe",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="procesmagazynowy",
            name="data_cofniecia",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="procesmagazynowy",
            name="operacja_powiazana",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operacje_cofajace",
                to="core.procesmagazynowy",
            ),
        ),
        migrations.AddField(
            model_name="procesmagazynowy",
            name="powod_cofniecia",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="stanmagazynowy",
            name="zarezerwowano",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="zamowienie",
            name="kwota_koncowa",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="zamowienie",
            name="numer",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="zamowienie",
            name="rabat_typ",
            field=models.CharField(
                choices=[
                    ("BRAK", "Brak rabatu"),
                    ("PROCENT", "Procentowy"),
                    ("KWOTA", "Kwotowy"),
                ],
                default="BRAK",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="zamowienie",
            name="rabat_wartosc",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="platnosc",
            name="rabat",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="pozycjazamowienia",
            name="rozmiar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.rozmiarblachy",
            ),
        ),
        migrations.AlterField(
            model_name="procesmagazynowy",
            name="pracownik",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="procesy_magazynowe",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="procesmagazynowy",
            name="typ",
            field=models.CharField(
                choices=[
                    ("PRZYJECIE", "Przyjęcie materiału"),
                    ("WYDANIE", "Wydanie materiału"),
                    ("INWENTARYZACJA", "Inwentaryzacja"),
                    ("COFNIECIE", "Cofnięcie operacji"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rozmiarblachy",
            name="szerokosc_mm",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="rozmiarblachy",
            name="wysokosc_mm",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="zamowienie",
            name="status",
            field=models.CharField(
                choices=[
                    ("ROBOCZE", "Robocze"),
                    ("ZATWIERDZONE", "Zatwierdzone"),
                    ("W_REALIZACJI", "W realizacji"),
                    ("WYKONANE", "Wykonane"),
                    ("GOTOWE_DO_ODBIORU", "Gotowe do odbioru"),
                    ("ZAKONCZONE", "Zakończone"),
                    ("ANULOWANE", "Anulowane"),
                ],
                default="ROBOCZE",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="Zadanie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rola_docelowa",
                    models.CharField(
                        choices=[
                            ("MAGAZYN", "Magazynier"),
                            ("PRODUKCJA", "Pracownik produkcji"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOWE", "Nowe"),
                            ("W_REALIZACJI", "W realizacji"),
                            ("ZREALIZOWANE", "Zrealizowane"),
                            ("ODRZUCONE", "Odrzucone"),
                        ],
                        default="NOWE",
                        max_length=20,
                    ),
                ),
                ("data_utworzenia", models.DateTimeField(auto_now_add=True)),
                ("data_zakonczenia", models.DateTimeField(blank=True, null=True)),
                ("uwagi", models.TextField(blank=True)),
                (
                    "pozycja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zadania",
                        to="core.pozycjazamowienia",
                    ),
                ),
                (
                    "przypisany_pracownik",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "typ_uslugi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.typuslugi",
                    ),
                ),
            ],
        ),
    ]
