# Generated by Django 4.2.27 on 2026-06-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_cena_pozycjazamowienia_cena_jednostkowa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="procesmagazynowy",
            name="typ",
            field=models.CharField(
                choices=[
                    ("PRZYJECIE", "Przyjęcie materiału"),
                    ("WYDANIE", "Wydanie materiału"),
                    ("REZERWACJA", "Rezerwacja materiału"),
                    ("ZWOLNIENIE_REZERWACJI", "Zwolnienie rezerwacji"),
                    ("INWENTARYZACJA", "Inwentaryzacja"),
                    ("COFNIECIE", "Cofnięcie operacji"),
                ],
                max_length=40,
            ),
        ),
    ]
