# Generated by Django 4.2.27 on 2026-06-25 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_procesmagazynowy_typ"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stanmagazynowy",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="pozycjazamowienia",
            name="stan_magazynowy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.stanmagazynowy",
            ),
        ),
        migrations.AddField(
            model_name="stanmagazynowy",
            name="rozmiar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.rozmiarblachy",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stanmagazynowy",
            unique_together={("magazyn", "material", "rozmiar")},
        ),
    ]
