# Generated by Django 4.2.27 on 2026-06-25 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_stanmagazynowy_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="procesmagazynowy",
            name="rozmiar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.rozmiarblachy",
            ),
        ),
    ]
