# Generated by Django 4.2.27 on 2026-06-25 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_procesmagazynowy_rozmiar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pozycjazamowienia",
            name="material",
        ),
        migrations.RemoveField(
            model_name="pozycjazamowienia",
            name="rozmiar",
        ),
    ]
