# Generated by Django 4.2.27 on 2026-06-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_pozycjazamowienia_material_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pozycjazamowienia",
            name="typ_uslugi",
        ),
        migrations.AddField(
            model_name="pozycjazamowienia",
            name="uslugi",
            field=models.ManyToManyField(
                blank=True, related_name="pozycje_zamowienia", to="core.typuslugi"
            ),
        ),
    ]
